/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#541532",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#3a001a",
        "on-tertiary-fixed-variant": "#42465c",
        "on-primary-fixed-variant": "#7d224d",
        "wood-bark": "#4A3B34",
        "on-background": "#1b1c1a",
        "surface-container-high": "#eae8e5",
        "on-surface": "#1b1c1a",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#ddbbea",
        "on-tertiary-container": "#cacde9",
        "surface-container-highest": "#e4e2df",
        "on-secondary-fixed": "#420c00",
        "surface-bright": "#fbf9f6",
        "inverse-on-surface": "#f2f0ed",
        "secondary": "#de074b",
        "meadow-green": "#8BA88E",
        "surface-cream": "#FFFFFF",
        "error": "#ba1a1a",
        "surface-container": "#efeeeb",
        "on-primary-container": "#e6c3f4",
        "tertiary-fixed": "#dee1fd",
        "on-primary": "#ffffff",
        "divine-yellow": "#F9FC11",
        "outline-variant": "#cec3cd",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#631000",
        "on-secondary-fixed-variant": "#ad3c1f",
        "surface-container-low": "#f5f3f0",
        "surface-dim": "#dbdad7",
        "error-container": "#ffdad6",
        "surface-variant": "#e4e2df",
        "background": "#fbf9f6",
        "secondary-container": "#b8063d",
        "primary-container": "#af2e67",
        "surface": "#fbf9f6",
        "outline": "#7d747d",
        "inverse-surface": "#30312f",
        "on-tertiary-fixed": "#161a2e",
        "primary-fixed": "#ffdce8",
        "tertiary-fixed-dim": "#c2c5e0",
        "secondary-fixed-dim": "#ffb4a3",
        "tertiary": "#eb6a33",
        "tertiary-container": "#d65520",
        "on-secondary": "#ffffff",
        "inverse-primary": "#ddbbea",
        "on-surface-variant": "#4b454d",
        "secondary-fixed": "#ffece6",
        "surface-tint": "#70547d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "section-gap-sm": "64px",
        "container-max": "1200px",
        "base": "8px",
        "section-gap-lg": "120px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "quote": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-xl-mobile": ["Playfair Display", "serif"],
        "headline-xl": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "quote": ["22px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg": ["36px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "headline-xl-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "headline-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
